# Generated by Django 6.1 on 2026-08-28 08:53

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Alumno',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100)),
                ('apellidos', models.CharField(max_length=150)),
                ('carrera', models.CharField(max_length=150)),
                ('curso', models.CharField(max_length=50)),
                ('email', models.EmailField(max_length=254, unique=True)),
                ('foto', models.ImageField(blank=True, null=True, upload_to='alumnos/')),
            ],
        ),
        migrations.CreateModel(
            name='Clase',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha', models.DateField()),
                ('hora_inicio', models.TimeField()),
                ('asistencia_abierta', models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name='Grupo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100)),
                ('asignatura', models.CharField(max_length=150)),
            ],
        ),
        migrations.CreateModel(
            name='Profesor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100)),
                ('apellidos', models.CharField(max_length=150)),
                ('email', models.EmailField(max_length=254, unique=True)),
                ('foto', models.ImageField(blank=True, null=True, upload_to='profesores/')),
            ],
        ),
        migrations.CreateModel(
            name='Asistencia',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('estado', models.CharField(choices=[('presente', 'Presente'), ('tarde', 'Tarde'), ('ausente', 'Ausente')], default='ausente', max_length=20)),
                ('hora_registro', models.TimeField(blank=True, null=True)),
                ('alumno', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='asistencia.alumno')),
                ('clase', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='asistencia.clase')),
            ],
        ),
        migrations.AddField(
            model_name='clase',
            name='grupo',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='asistencia.grupo'),
        ),
        migrations.AddField(
            model_name='alumno',
            name='grupo',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='asistencia.grupo'),
        ),
        migrations.CreateModel(
            name='Justificacion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('motivo', models.TextField()),
                ('documento', models.FileField(blank=True, null=True, upload_to='justificaciones/')),
                ('aceptada', models.BooleanField(default=False)),
                ('asistencia', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='asistencia.asistencia')),
            ],
        ),
        migrations.AddField(
            model_name='grupo',
            name='profesor',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='asistencia.profesor'),
        ),
    ]
