# Generated by Django 6.1 on 2026-08-28 11:13

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('asistencia', '0002_alumno_password'),
    ]

    operations = [
        migrations.AddField(
            model_name='clase',
            name='token_qr',
            field=models.UUIDField(default=uuid.uuid4, editable=False),
        ),
        migrations.AddConstraint(
            model_name='asistencia',
            constraint=models.UniqueConstraint(fields=('alumno', 'clase'), name='asistencia_unica_por_alumno_clase'),
        ),
    ]
