# Generated by Django 6.1 on 2026-08-28 12:18

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('asistencia', '0004_solicitudsoporte'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='justificacion',
            name='aceptada',
        ),
        migrations.AddField(
            model_name='justificacion',
            name='estado',
            field=models.CharField(choices=[('pendiente', 'Pendiente'), ('aprobada', 'Aprobada'), ('rechazada', 'Rechazada')], default='pendiente', max_length=20),
        ),
        migrations.AddField(
            model_name='justificacion',
            name='fecha_solicitud',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='justificacion',
            name='documento',
            field=models.ImageField(blank=True, null=True, upload_to='justificaciones/'),
        ),
    ]
