# Generated by Django 6.1 on 2026-09-01 18:59

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('asistencia', '0005_remove_justificacion_aceptada_justificacion_estado_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='clase',
            name='token_qr_generado_en',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='clase',
            name='token_qr',
            field=models.UUIDField(default=uuid.uuid4, editable=False, unique=True),
        ),
    ]
