# Generated by Django 6.1 on 2026-10-01 17:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('asistencia', '0006_clase_token_qr_generado_en_alter_clase_token_qr'),
    ]

    operations = [
        migrations.AddField(
            model_name='grupo',
            name='color',
            field=models.CharField(choices=[('blanco', 'Blanco'), ('rosa', 'Rosa'), ('rojo', 'Rojo'), ('naranja', 'Naranja'), ('azul', 'Azul'), ('verde', 'Verde'), ('amarillo', 'Amarillo'), ('violeta', 'Violeta')], default='blanco', max_length=20),
        ),
    ]
