# Generated by Django 6.1 on 2026-10-01 19:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('asistencia', '0007_grupo_color'),
    ]

    operations = [
        migrations.AddField(
            model_name='clase',
            name='latitud_profesor',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='clase',
            name='longitud_profesor',
            field=models.FloatField(blank=True, null=True),
        ),
    ]
