# Generated by Django 6.1 on 2026-10-05 06:49

import asistencia.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('asistencia', '0008_clase_latitud_profesor_clase_longitud_profesor'),
    ]

    operations = [
        migrations.AlterField(
            model_name='alumno',
            name='foto',
            field=models.ImageField(blank=True, null=True, upload_to='alumnos/', validators=[asistencia.models.validar_foto_perfil]),
        ),
        migrations.AlterField(
            model_name='profesor',
            name='foto',
            field=models.ImageField(blank=True, null=True, upload_to='profesores/', validators=[asistencia.models.validar_foto_perfil]),
        ),
    ]
